app/controllers/api/v1/organisation_controller.rb
app/controllers/base/sessions_controller.rb
app/javascript/packs/autocomplete.js
app/javascript/packs/stylesheets/govuk.scss
app/services/cognito/sign_in_user.rb
app/views/base/registrations/new.html.erb

Updated auto complete to know only show results in they return less than a 100 results.

Auto complete functionality updated

---

.gitignore
README.md

This is a guide for installing and running the application in the local developer environment. It was taken and reworked from the following confluence page https://crowncommercialservice.atlassian.net/wiki/spaces/PMP/pages/835158050/How+to+set+up+the+Print+Marketplace+IDAM+on+a+CCS+laptop

Add a guide to the README for installing the application

---

app/views/base/registrations/new.html.erb
app/views/base/users/_new_password_required.html.erb
app/views/base/users/_sms_mfa.html.erb

Using a HTML validator I was able to check each page and fix any issues found

Accessibility - Fix invalid html

---

app/helpers/application_helper.rb
app/javascript/packs/stylesheets/govuk.scss
app/views/base/registrations/domain_not_on_whitelist.html.erb
app/views/base/registrations/new.html.erb
app/views/base/users/_new_password_required.html.erb
app/views/base/users/_sms_mfa.html.erb
app/views/base/users/confirm_new.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
config/locales/en.yml

> - Update CSS for navigation
> - Add page titles to pages

PMP-35 -Accessibility fixes

---

.rubocop.yml
.travis.yml
Gemfile
Gemfile.lock
app/services/cognito/sign_up_user.rb
config/locales/en.yml
lib/tasks/default.rake
lib/tasks/rubocop.rake
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb

> - Add specs to make sure error messages are correct
> - Add default rake task
> - Make changes so travis runs
> - Add tests for confirm password reset
> - Add tests for confirm sign up
> - Add tests for the forgot password
> - Add tests for signing up user

Add specs for the PMP project

---

app/controllers/api/v1/organisation_controller.rb
app/javascript/packs/autocomplete.js
app/views/base/registrations/new.html.erb
config/locales/en.yml

> - Update how the autocomplete works
> - Add check if no results
> - Make correct message appear when searching

PMP-85 - Autocomplete checks if no results

---

app/services/cognito/confirm_password_reset.rb
app/services/cognito/sign_up_user.rb

Reverted Password policy

---

app/models/concerns/password_validator.rb
app/services/cognito/confirm_password_reset.rb
app/services/cognito/respond_to_challenge.rb
app/services/cognito/sign_up_user.rb
app/views/layouts/_password-strength.html.erb
config/locales/en.yml
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/respond_to_challenge_spec.rb
spec/services/cognito/sign_up_user_spec.rb

> - Remove the checking of symbols from the password criteria on the front end
> - Create concern for password validation
> - Add testing for the password validator
> - Add tests for respond to challenge

PMP-10 - add new validation on password symbols

---

app/services/cognito/confirm_password_reset.rb
app/services/cognito/confirm_sign_up.rb
app/services/cognito/forgot_password.rb
app/services/cognito/resend_confirmation_code.rb
app/services/cognito/sign_up_user.rb
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb

> - When the user registers, their email is downcased
> - Make sure email is always downcased

PMP - 90 - Make sure emails are lower case

---

config/initializers/arask.rb
lib/tasks/domains.rake
lib/tasks/organisations.rake

> - Add rake task to add email domains
> - Update the rake task for email domains
> - Update tasks so they run as arask job
> - Update the rake task to use correct model name

PM-17 - Create task for importing email domains from salesforce api

---

config/routes.rb

Remove routes that have been removed in main

Remove unused routes

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
app/views/layouts/error.html.erb
config/initializers/canonical_rails.rb

Add canonical urls to application

PM-68 - Add canonical urls

---

app/controllers/application_controller.rb
app/controllers/base/passwords_controller.rb
app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/controllers/base/users_controller.rb
spec/controllers/application_controller_spec.rb

> - Add logging for signing in
> - Add more logging information to the application
> - Add specs for the get_error_list method

PM-67 - Add additional logging into the app

---

Gemfile
Gemfile.lock
config/initializers/cf_vault.rb

> - Add the Vault gem
> - Add vault config

PM-71 -Config vault

---

app/controllers/base/users_controller.rb
app/views/base/registrations/new.html.erb
app/views/base/users/_new_password_required.html.erb
app/views/shared/passwords/_edit.html.erb

> - Add aria label for the password section
> - Remove hidden errors that cause issue with the screen reader

PM-69 - Accessibility - make sure password requirements are read by screen reader

---

Gemfile
Gemfile.lock
config/initializers/cf_vault.rb

Reverts Crown-Commercial-Service/pmp-idam#80

Revert "Revert "PM-71 -Config vault""

---

app/services/cognito/create_user_from_cognito.rb

In some of my refactoring I accidentally removed a class that I shouldn't have.
I am now re adding it which should fix some issues.

Add class that was wrongfully taken out

---

app/services/salesforce_import/organisations.rb
data/test_organisations.csv
db/migrate/20211125165513_add_columns_to_organisations_table.rb
db/schema.rb
spec/models/organisation_spec.rb

- Add columns to the table
- Update the task to import address and URN as well as organisations
- Add tests for the creation of the summary line

Update the data to have the URN and a summary line from the address

---

app/controllers/api/v1/organisation_controller.rb
app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/javascript/packs/autocomplete.js
app/javascript/packs/error-links.js
app/models/organisation.rb
app/services/cognito/sign_up_user.rb
app/views/base/registrations/new.html.erb
config/locales/en.yml
spec/controllers/api/v1/organisation_controller_spec.rb
spec/controllers/base/registrations_controller_spec.rb
spec/models/organisation_spec.rb
spec/services/cognito/sign_up_user_spec.rb

- Add the summary line as the selected option
- Update the JS and add validation for the search
- Add tests for changes to search

Show summary line when user searches for their organisation

---

config/locales/en.yml

See:
- https://crowncommercialservice.atlassian.net/browse/PM-81
- https://crowncommercialservice.atlassian.net/browse/PM-84

Make a couple of copy changes

---

config/secrets.yml

Copied from: https://github.com/Crown-Commercial-Service/tailspend-idam/pull/28
> Instructions:
> 
> Adding the secrets.yml to pull from the SECRET_KEY_BASE env variable
> 
> To generate a key run RAILS_ENV=production rake secret

Add the secret key to the config

---

app/controllers/base/sessions_controller.rb
app/services/cognito/sign_in_user.rb
config/locales/en.yml
spec/services/cognito/sign_in_user_spec.rb

From https://github.com/Crown-Commercial-Service/tailspend-idam/pull/29
> Open redirect issue now fixed
> Also fixed unsuccessful redirects on sign in the cases in which account is not confirmed or when it requires password reset

Fixed ITHC issue found in Tailspend

---

app/controllers/base/passwords_controller.rb
app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/controllers/base/users_controller.rb
app/helpers/application_helper.rb
app/services/cognito/sign_in_user.rb
app/services/text_encryptor.rb
app/views/base/sessions/new.html.erb
app/views/base/users/confirm_new.html.erb
config/locales/en.yml
config/secrets.yml
package.json
spec/controllers/base/passwords_controller_spec.rb
spec/controllers/base/registrations_controller_spec.rb
spec/controllers/base/users_controller_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/text_encryptor_spec.rb
yarn.lock

- Hide PII from URL
- Various security fixes

STAGING - Release 1.4.0

---

app/controllers/base/passwords_controller.rb
app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/controllers/base/users_controller.rb
app/helpers/application_helper.rb
app/services/cognito/sign_in_user.rb
app/services/text_encryptor.rb
app/views/base/sessions/new.html.erb
app/views/base/users/confirm_new.html.erb
config/locales/en.yml
config/secrets.yml
package.json
spec/controllers/base/passwords_controller_spec.rb
spec/controllers/base/registrations_controller_spec.rb
spec/controllers/base/users_controller_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/text_encryptor_spec.rb
yarn.lock

- Hide PII from URL
- Various security fixes

PRODUCTION - Release 1.4.0

---

app/services/cognito/forgot_password.rb
spec/services/cognito/forgot_password_spec.rb

- Add test to catch the error
- Update the regex to allow for domains with dashes

Update email validation for forgot password

---

app/views/base/registrations/new.html.erb
config/locales/en.yml

[PM-91](https://crowncommercialservice.atlassian.net/browse/PM-91)
This is what the page looks like now:

PM-91 - Add text above the organisation box

---

.gitignore
app/models/concerns/password_validator.rb
app/models/pwned_password.rb
app/services/pwned_passwords.rb
config/locales/en.yml
data/test_pwned_passwords.json
db/migrate/20220429124605_create_pwned_passwords.rb
db/migrate/20220503113745_add_pwned_passwords.rb
db/schema.rb
lib/tasks/pwned_passwords.rake
lib/tasks/quiet_rspec.rake
spec/controllers/base/passwords_controller_spec.rb
spec/models/pwned_password_spec.rb
spec/rails_helper.rb
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/sign_up_user_spec.rb
spec/support/random_password_generator.rb

Ticket: [PM-93](https://crowncommercialservice.atlassian.net/browse/PM-93)
Added a list of pwarned passwords to check against. This is to prevent users using common passwords that may be easier to guess.
I added a job to import the pwned passwords from the NCSC every month in case it gets updated.

PM-93 - Added a list of pwarnd passwords to check against

---

config/environments/production.rb

Ticket: https://crowncommercialservice.atlassian.net/browse/PM-96
Add the application URIs dynamically from GPaaS

PM-96 - Fix issue with GPaaS generated domains

---

config/environments/production.rb

Continuation of https://github.com/Crown-Commercial-Service/pmp-idam/pull/232

Make it work for all domains

---

config/application.rb

Fixes some issues in: https://github.com/Crown-Commercial-Service/pmp-idam/pull/234

Remove any logic to select domain and allow all of them

---

app/views/layouts/_contact_us.html.erb
app/views/layouts/_footer.html.erb
config/locales/en.yml

Ticket: [PM-90](https://crowncommercialservice.atlassian.net/browse/PM-90)

PM-90 - Update the contact us link in the footer

---

app/services/cognito/sign_in_user.rb

Added the ensure to make sure this method actually works as expected

Make sure the go then wait actually works when an exception is raised

---

app/services/salesforce_import/domains.rb

Ticket: [PM-108](https://crowncommercialservice.atlassian.net/browse/PM-108)
Make sure all email domains are lower case when we import them
[PM-108]: https://crowncommercialservice.atlassian.net/browse/PM-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PM-108 - Make sure all email domains are lower case when we import them

---

app/controllers/errors_controller.rb
app/views/errors/internal_error.html.erb
app/views/errors/not_found.html.erb
app/views/errors/service_unavailable.html.erb
app/views/errors/unacceptable.html.erb
app/views/layouts/_header-banner.html.erb
config/locales/en.yml
config/routes.rb

Ticket: [PM-117](https://crowncommercialservice.atlassian.net/browse/PM-117)
[PM-117]: https://crowncommercialservice.atlassian.net/browse/PM-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Create the service unavailable page

---

.cfignore
config/application.rb

Depends on: https://github.com/Crown-Commercial-Service/ccs-pmp-aws-infrastructure/pull/34

Remove code relating to GPaaS as we no longer use this platform anymore
